#include "main.h"
#include "display.h"

static void delay(long tiks) {
	for (long i = 0; i < tiks; i++)
		;
}

int main() {
	RCC->APB2ENR |= RCC_APB2ENR_IOPBEN | RCC_APB2ENR_IOPAEN;
	
	GPIOB->CRH &= ~(GPIO_CRH_MODE9 | GPIO_CRH_CNF9);
	GPIOB->CRH &= ~(GPIO_CRH_MODE10 | GPIO_CRH_CNF10);
	GPIOB->CRH &= ~(GPIO_CRH_MODE11 | GPIO_CRH_CNF11);
	GPIOB->CRH &= ~(GPIO_CRH_MODE12 | GPIO_CRH_CNF12);
	GPIOB->CRH &= ~(GPIO_CRH_MODE13 | GPIO_CRH_CNF13);
	GPIOB->CRH &= ~(GPIO_CRH_MODE14 | GPIO_CRH_CNF14);
	GPIOB->CRH &= ~(GPIO_CRH_MODE15 | GPIO_CRH_CNF15);
	
	GPIOB->CRH |= GPIO_CRH_MODE9;
	GPIOB->CRH |= GPIO_CRH_MODE10;
	GPIOB->CRH |= GPIO_CRH_MODE11;
	GPIOB->CRH |= GPIO_CRH_MODE12;
	GPIOB->CRH |= GPIO_CRH_MODE13;
	GPIOB->CRH |= GPIO_CRH_MODE14;
	GPIOB->CRH |= GPIO_CRH_MODE15;
	
	GPIOA->CRH &= ~(GPIO_CRH_MODE13 | GPIO_CRH_CNF13);
	GPIOA->CRH &= ~(GPIO_CRH_MODE14 | GPIO_CRH_CNF14);
	GPIOA->CRH &= ~(GPIO_CRH_MODE15 | GPIO_CRH_CNF15);
	
	GPIOA->CRH |= GPIO_CRH_MODE13;
	GPIOA->CRH |= GPIO_CRH_MODE14;
	GPIOA->CRH |= GPIO_CRH_MODE15;
	
	Init();
	
	while(1) {

	}
}
